### ISSUE TITLE
Udemy Certificate Error

### ISSUE THREAD

**Issue by ArpitVishnoi** [shubho0908/Certificate-Generator#6]
Udemy certificate is not getting generated

**Comment by shubho0908** [comment]
It's working fine from my end, btw if you are using the site on mobile then it might not work because I didn't made it responsive and functioning for small devices.

**Comment by omsnch** [comment]
Hello! first of all I really want to thank you for this tool that you have made.
Although I need some help and even want to make a request 🙏 since I have not been able to generate diplomas on my own (IDK why),I used the site :
https://shubho-certificate-generator.netlify.app/
Could you add these improvements?

I compared an original udemy diploma with a generated one and found some interesting things:

The background color of an original Udemy diploma is:
#f8f9fb
rgba(248,249,251,255) 
according to a color detector page

and the one generated by your site is:
#fbfafa
rgba(251,250,250,255)

Another question is that in the original diploma it is: "Instructors" and not "Instructor" even when only one person did the course.

And lastly, it is not so important but in the course title section, is it possible to add "new text lines" "enter" ?

Again thank you very much and it would be great if you could add these improvements for others who find this tool.


![Compare](https://github.com/shubho0908/Certificate-Generator/assets/78331451/bb7419f1-c533-4c7c-9e59-5be0c9f29e31)

**Comment by omsnch** [comment]
Hello! first of all I really want to thank you for this tool that you have made.
Although I need some help and even want to make a request 🙏 since I have not been able to generate diplomas on my own (IDK why),I used the site :
https://shubho-certificate-generator.netlify.app/
Could you add these improvements?

I compared an original udemy diploma with a generated one and found some interesting things:

The background color of an original Udemy diploma is:
#f8f9fb
rgba(248,249,251,255)
according to a color detector page

and the one generated by your site is:
#fbfafa
rgba(251,250,250,255)

Another question is that in the original diploma it is: "Instructors" and not "Instructor" even when only one person did the course.

And lastly, it is not so important but in the course title section, is it possible to add "new text lines" "enter" ?

Again thank you very much and it would be great if you could add these improvements for others who find this tool.


![Uploading Compare.png…]()

**Comment by shubho0908** [comment]
Thank you so much for addressing these improvements, I actually made this tool for fun and never thought that it would be useful to someone. That's why I actually didn't even update this project after that, but I'll soon work on the improvements.
